# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-23 22:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audits_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audit',
            name='sched_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
